/* Guest workspace: shared guest data; view preferences stay on this device. */
const guestNormalize=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const guestUnlinked=g=>!g.baseIncluded&&Boolean(g.respondedAt);
const guestDni=g=>String(g.dni||'').replace(/[.\s-]/g,'');
const validGuestDni=g=>/^\d{7,8}$/.test(guestDni(g));
const guestDietKey=g=>{const m=guestNormalize(g.menu);return /celiac|sin gluten|sin tacc/.test(m)?'celiac':/vegan/.test(m)?'vegan':/vegetarian/.test(m)?'vegetarian':/^(ninguna|ninguno|comun|menu comun|normal|sin restricciones)$/.test(m)?'common':m?'other':'unknown'};
const guestMenuLabel=g=>({common:'Menú común',unknown:'Menú por confirmar'})[guestDietKey(g)]||g.menu;
const guestDietLabels={celiac:'Celíacos',vegetarian:'Vegetarianos',vegan:'Veganos',other:'Otras restricciones',common:'Menú común',unknown:'Sin informar'};
const guestColumns={group:'Grupo',ageGroup:'Edad',status:'Confirmación',menu:'Menú',dni:'DNI',table:'Mesa / living',civil:'Civil',notes:'Notas'};
let guestPrefs={mode:'cards',columns:['group','ageGroup','status','menu','dni','table'],metrics:['confirmed','pending','celiac','missing'],saved:[]};
try{const p=JSON.parse(localStorage.getItem('fp-guest-workspace')||'null');if(p&&Array.isArray(p.columns)&&Array.isArray(p.metrics)&&Array.isArray(p.saved))guestPrefs={...guestPrefs,...p}}catch{}
let guestView='all',guestFilters={status:'',diet:'',age:'',group:'',dni:'',civil:'',seat:''},guestSort='name',guestSelection=new Set();
function persistGuestPrefs(){try{localStorage.setItem('fp-guest-workspace',JSON.stringify(guestPrefs))}catch{toast('No se pudo guardar la vista en este dispositivo.')}}
function guestSeat(g){return db.layout?.items.find(t=>t.guests.includes(g.id))?.name||g.table||''}
function guestFilteredRows(){return db.guests.filter(g=>{
 if(guestView==='review'?!guestUnlinked(g):guestUnlinked(g))return false;
 if(guestView==='confirmed'&&g.status!=='Confirmado'||guestView==='pending'&&g.status!=='Pendiente'||guestView==='country'&&g.status!=='Confirmado'||guestView==='catering'&&g.status!=='Confirmado'||guestView==='civil'&&!g.civil)return false;
 if(guestFilters.status&&g.status!==guestFilters.status||guestFilters.diet&&guestDietKey(g)!==guestFilters.diet||guestFilters.age&&g.ageGroup!==guestFilters.age||guestFilters.group&&g.group!==guestFilters.group||guestFilters.dni==='missing'&&validGuestDni(g)||guestFilters.dni==='ready'&&!validGuestDni(g)||guestFilters.civil==='yes'&&!g.civil||guestFilters.civil==='no'&&g.civil||guestFilters.seat==='missing'&&guestSeat(g)||guestFilters.seat==='ready'&&!guestSeat(g))return false;
 return !search||guestNormalize([g.name,g.baseName,g.group,g.dni,g.menu,g.notes].join(' ')).includes(guestNormalize(search));
 }).sort((a,b)=>{const value=g=>guestSort==='name'?g.name:guestSort==='table'?guestSeat(g):g[guestSort]||'';return String(value(a)).localeCompare(String(value(b)),'es',{numeric:true})||a.name.localeCompare(b.name,'es')})}
function guestReset(view='all'){guestView=view;guestFilters={status:'',diet:'',age:'',group:'',dni:'',civil:'',seat:''};search='';filter='';guestSelection.clear();render()}
function guestOptions(values,current,empty){return `<option value="">${empty}</option>`+values.map(([v,l])=>`<option value="${esc(v)}" ${current===v?'selected':''}>${esc(l)}</option>`).join('')}
function guestFilterControl(key,label,values){return `<label>${label}<select data-gfilter="${key}">${guestOptions(values,guestFilters[key],'Todos')}</select></label>`}
function guestMetric(key,label,value,sub){return `<button class="guest-metric" data-metric="${key}"><span>${label}</span><strong>${value}</strong><small>${sub} ↗</small></button>`}
function guestMobileView(){
 const people=db.guests.filter(g=>!guestUnlinked(g)),confirmed=people.filter(g=>g.status==='Confirmado'),review=db.guests.filter(guestUnlinked).length,list=guestFilteredRows();
 const metrics={confirmed:['Confirmados',confirmed.length,`${people.length} en la lista`],pending:['Sin confirmar',people.filter(g=>g.status==='Pendiente').length,'Ver pendientes'],celiac:['Celíacos',confirmed.filter(g=>guestDietKey(g)==='celiac').length,'Entre confirmados'],vegetarian:['Vegetarianos',confirmed.filter(g=>guestDietKey(g)==='vegetarian').length,'Entre confirmados'],minor:['Menores',confirmed.filter(g=>g.ageGroup==='Menor').length,'Entre confirmados'],missing:['Falta DNI',confirmed.filter(g=>!validGuestDni(g)).length,'Entre confirmados'],noseat:['Sin ubicación',confirmed.filter(g=>!guestSeat(g)).length,'Entre confirmados'],civil:['Para el civil',people.filter(g=>g.civil).length,'Lista elegida']};
 const progress=people.length?Math.round(confirmed.length/people.length*100):0;
 const country=guestView==='country',menu=guestView==='catering';
 const cols=country?['dni','status']:menu?['menu','ageGroup','table']:guestPrefs.columns;
 const visibleSelection=list.filter(g=>guestSelection.has(g.id));
 return `<section class="guest-workspace"><div class="guest-heading"><div><p class="eyebrow">FACU & PICHU · 21 NOV 2026</p><h1>Nuestra gente<span>♡</span></h1><p>Una lista para organizar cada encuentro.</p></div><div class="guest-heading-actions"><button class="quiet" id="guest-customize">⚙ Personalizar</button><button class="primary" id="add">+ Invitado</button></div></div>
 <div class="guest-metrics">${guestPrefs.metrics.filter(k=>metrics[k]).map(k=>guestMetric(k,...metrics[k])).join('')}</div>
 <div class="guest-progress"><span><b>${progress}%</b> de la lista confirmó</span><progress max="100" value="${progress}" aria-label="Porcentaje confirmado"></progress><small>${people.filter(g=>g.status==='No viene').length} no vienen</small></div>
 ${review?`<div class="guest-review-banner"><span><b>${review} respuestas para revisar.</b> No se suman a estos contadores hasta vincularlas o agregarlas a la lista.</span><button class="quiet" data-gview="review">Revisar cruce →</button></div>`:''}
 <div class="guest-tabs" aria-label="Vistas de invitados">${[['all','Todos'],['confirmed','Confirmados'],['pending','Pendientes'],['country','Country · DNI'],['catering','Catering'],['civil','Civil'],['review','Revisar cruce']].map(([v,l])=>`<button data-gview="${v}" class="${guestView===v?'active':''}" aria-pressed="${guestView===v}">${l}</button>`).join('')}</div>
 <div class="guest-panel"><div class="guest-searchbar"><input type="search" id="guest-search" aria-label="Buscar invitados" placeholder="Buscar nombre, grupo, DNI o menú…" value="${esc(search)}"><button class="quiet" id="guest-clear">Limpiar filtros</button><button class="quiet" id="guest-save-view">Guardar vista</button></div>
 <details class="guest-filters" ${Object.values(guestFilters).some(Boolean)?'open':''}><summary>Filtros ${Object.values(guestFilters).filter(Boolean).length?'· '+Object.values(guestFilters).filter(Boolean).length+' activos':'· combinar por menú, grupo, edad y más'}</summary><div class="guest-filter-grid">${guestFilterControl('status','Confirmación',['Confirmado','Pendiente','No viene'].map(v=>[v,v]))}${guestFilterControl('diet','Menú',Object.entries(guestDietLabels))}${guestFilterControl('age','Edad',['Adulto','Menor','Sin informar'].map(v=>[v,v]))}${guestFilterControl('group','Grupo',[...new Set(db.guests.map(g=>g.group).filter(Boolean))].sort().map(v=>[v,v]))}${guestFilterControl('dni','DNI',[['missing','Falta / revisar'],['ready','Cargado']])}${guestFilterControl('seat','Ubicación',[['missing','Sin mesa / living'],['ready','Con ubicación']])}${guestFilterControl('civil','Civil',[['yes','Invitado al civil'],['no','No seleccionado']])}</div></details>
 ${guestPrefs.saved.length?`<div class="guest-saved"><span>Mis vistas</span>${guestPrefs.saved.map((v,i)=>`<button class="quiet" data-saved-view="${i}">${esc(v.name)}</button>`).join('')}</div>`:''}
 ${country?`<div class="guest-purpose"><h2>Acceso al Grand Bell</h2><p>Solo confirmados de la lista. Cargá los documentos y descargá <b>solo DNI</b> o <b>nombre + DNI</b>. Los documentos faltantes o repetidos se señalan antes de exportar.</p><div class="guest-purpose-counts"><b>${list.filter(validGuestDni).length} con DNI</b><span>${list.filter(g=>!validGuestDni(g)).length} faltantes o inválidos</span></div><button class="primary" id="country-export">Preparar lista para el country</button></div>`:''}
 ${menu?`<div class="guest-purpose"><h2>Menús de los confirmados</h2><div class="guest-menu-summary">${Object.entries(guestDietLabels).map(([k,l])=>`<button class="quiet" data-menu-pick="${k}">${l} <b>${list.filter(g=>guestDietKey(g)===k).length}</b></button>`).join('')}</div><p>La exportación de catering incluye nombre, menú, edad y ubicación.</p></div>`:''}
 <div class="guest-listbar"><b>${list.length} ${list.length===1?'persona':'personas'}${visibleSelection.length?' · '+visibleSelection.length+' seleccionadas':''}</b><div><label class="sr-only" for="guest-sort">Ordenar</label><select id="guest-sort">${[['name','Nombre A–Z'],['group','Grupo'],['status','Confirmación'],['menu','Menú'],['table','Mesa / living']].map(([v,l])=>`<option value="${v}" ${guestSort===v?'selected':''}>${l}</option>`).join('')}</select><div class="guest-toggle"><button data-mode="cards" aria-label="Vista de tarjetas" aria-pressed="${guestPrefs.mode==='cards'}">Tarjetas</button><button data-mode="table" aria-label="Vista de tabla" aria-pressed="${guestPrefs.mode==='table'}">Tabla</button></div></div></div>
 <div class="guest-bulkbar"><label><input type="checkbox" id="guest-select-all" ${list.length&&visibleSelection.length===list.length?'checked':''}> Seleccionar lista visible</label>${visibleSelection.length?`<button class="quiet" id="guest-bulk">Editar ${visibleSelection.length}</button><button class="quiet" id="guest-selection-clear">Quitar selección</button>`:''}<button class="quiet" id="guest-export">↓ Exportar${visibleSelection.length?' selección':' vista'}</button><button class="quiet" id="import">+ Importar nombres</button></div>
 ${list.length?guestPrefs.mode==='table'?`<div class="table-wrap guest-table"><table><thead><tr><th>Elegir</th><th>Nombre</th>${cols.filter(k=>guestColumns[k]).map(k=>`<th>${guestColumns[k]}</th>`).join('')}<th>Editar</th></tr></thead><tbody>${list.map(g=>`<tr><td>${guestCheck(g)}</td><td><b>${esc(g.name)}</b>${guestSource(g)}</td>${cols.filter(k=>guestColumns[k]).map(k=>`<td>${guestCell(g,k)}</td>`).join('')}<td><button class="quiet" data-edit="${esc(g.id)}">Editar</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="guest-cards">${list.map(g=>`<article class="guest-card"><div class="guest-card-title">${guestCheck(g)}<div><h2>${esc(g.name)}</h2>${guestSource(g)}</div><button class="quiet" data-edit="${esc(g.id)}" aria-label="Editar ${esc(g.name)}">Editar</button></div><div class="guest-card-fields">${cols.filter(k=>guestColumns[k]).map(k=>`<div class="guest-card-field ${k==='notes'?'wide':''}"><small>${guestColumns[k]}</small>${guestCell(g,k)}</div>`).join('')}</div>${guestUnlinked(g)?`<div class="guest-review-actions"><button class="primary" data-link-response="${esc(g.id)}">Vincular con la base</button><button class="quiet" data-accept-response="${esc(g.id)}">Es una persona nueva</button></div>`:''}</article>`).join('')}</div>`:`<div class="empty"><strong>${guestView==='civil'?'Armemos la lista del civil':'No hay personas en esta vista'}</strong>${guestView==='civil'?'Marcá “Invitado al civil” al editar una persona o usá la edición de varias personas.':'Probá limpiar los filtros o agregá un invitado.'}<button class="quiet" id="guest-empty-reset">Ver toda la lista</button></div>`}
 </div><p class="guest-footnote">Los datos se sincronizan entre dispositivos. Las vistas y la personalización se guardan en este navegador. Las respuestas nuevas del formulario todavía se importan manualmente.</p></section>`;
}
function guestCheck(g){return `<input type="checkbox" data-guest-check="${esc(g.id)}" aria-label="Seleccionar ${esc(g.name)}" ${guestSelection.has(g.id)?'checked':''}>`}
function guestSource(g){return guestUnlinked(g)?`<small class="guest-source">Respuesta sin vincular</small>${guestPrefs.mode==='table'?`<button class="quiet" data-link-response="${esc(g.id)}">Vincular</button><button class="quiet" data-accept-response="${esc(g.id)}">Persona nueva</button>`:''}`:g.respondedAt?'<small class="guest-source">✓ Formulario vinculado</small>':''}
function guestCell(g,k){if(k==='status')return `<select data-status="${esc(g.id)}" aria-label="Confirmación de ${esc(g.name)}">${['Pendiente','Confirmado','No viene'].map(s=>`<option ${s===g.status?'selected':''}>${s}</option>`).join('')}</select>`;if(k==='dni')return `<button class="guest-dni ${validGuestDni(g)?'ready':'missing'}" data-dni="${esc(g.id)}" aria-label="DNI de ${esc(g.name)}">${esc(g.dni||'+ Cargar DNI')}${g.dni&&!validGuestDni(g)?' · revisar':''}</button>`;if(k==='menu')return `<span class="guest-menu ${guestDietKey(g)}">${esc(guestMenuLabel(g))}</span>`;if(k==='table')return esc(guestSeat(g)||'Sin ubicación');if(k==='civil')return g.civil?'Invitado al civil':'—';if(k==='notes')return `<span class="guest-notes">${esc(g.notes||'—')}</span>`;return esc(g[k]||'—')}
function guestSelectedRows(){const list=guestFilteredRows(),selected=list.filter(g=>guestSelection.has(g.id));return selected.length?selected:list}
function guestExport(){const list=guestSelectedRows();if(guestView==='country')return guestCountryExport(list);if(!list.length)return toast('No hay personas para exportar.');const cols=guestView==='catering'?['menu','ageGroup','table']:guestPrefs.columns.filter(k=>guestColumns[k]);csv([['Nombre',...cols.map(k=>guestColumns[k])],...list.map(g=>[g.name,...cols.map(k=>k==='table'?guestSeat(g):k==='menu'?guestMenuLabel(g):k==='civil'?g.civil?'Sí':'No':g[k]||'')])],guestView==='catering'?'catering-confirmados.csv':'invitados-vista.csv')}
function guestCountryData(list){const counts=new Map();for(const g of db.guests.filter(g=>!guestUnlinked(g)&&g.status==='Confirmado'&&validGuestDni(g)))counts.set(guestDni(g),(counts.get(guestDni(g))||0)+1);return {ready:list.filter(g=>validGuestDni(g)&&counts.get(guestDni(g))===1),missing:list.filter(g=>!validGuestDni(g)),duplicates:list.filter(g=>validGuestDni(g)&&counts.get(guestDni(g))>1)}}
function guestCountryExport(list=guestFilteredRows()){const r=guestCountryData(list);modal('Lista para el country',`<div class="full"><p><b>${r.ready.length}</b> documentos listos · <b>${r.missing.length}</b> faltantes / inválidos · <b>${r.duplicates.length}</b> personas con DNI repetido.</p><p>Se exportan únicamente documentos válidos y no repetidos de los confirmados de esta vista. No se incluyen menús ni notas.</p>${r.missing.length?`<details><summary>Ver a quiénes falta DNI (${r.missing.length})</summary><p>${r.missing.map(g=>esc(g.name)).join('<br>')}</p></details>`:''}${r.duplicates.length?`<p class="guest-warning">Revisar DNI repetidos: ${r.duplicates.map(g=>esc(g.name)).join(', ')}</p>`:''}<label>Formato<select name="format"><option value="txt">Solo DNI · texto, uno por línea</option><option value="csv">Solo DNI · CSV para Excel</option><option value="names">Nombre y DNI · CSV para Excel</option></select></label></div>`,async d=>{if(!r.ready.length)return toast('Primero cargá los DNI faltantes o corregí los repetidos.');if(d.format==='txt')download(r.ready.map(guestDni).join('\r\n'),'country-solo-dni.txt','text/plain;charset=utf-8');else csv([d.format==='names'?['Nombre','DNI']:['DNI'],...r.ready.map(g=>d.format==='names'?[g.name,guestDni(g)]:[guestDni(g)])],d.format==='names'?'country-nombres-dni.csv':'country-solo-dni.csv');$('#modal').close()});$('#form button[type=submit]').textContent='Descargar lista'}
function guestEditDni(id){const g=db.guests.find(g=>g.id===id);modal('DNI · '+g.name,`<p class="full">Documento para el acceso al country. Dejalo vacío si aún no lo tenés.</p><label class="full">DNI<input name="dni" inputmode="numeric" autocomplete="off" value="${esc(g.dni||'')}" placeholder="Ej. 30123456"></label>`,async d=>{const dni=guestDni(d);if(dni&&!/^\d{7,8}$/.test(dni))return toast('Ingresá un DNI de 7 u 8 dígitos.');if(dni&&db.guests.some(x=>x.id!==id&&guestDni(x)===dni))return toast('Ese DNI ya está cargado en otra persona. Revisá el cruce.');const next=structuredClone(db);next.guests.find(x=>x.id===id).dni=dni;if(await save(next))$('#modal').close()})}
function guestCustomize(){modal('Tu dashboard, a tu manera',`<div class="full"><h3>Contadores</h3><div class="guest-check-grid">${Object.entries({confirmed:'Confirmados',pending:'Pendientes',celiac:'Celíacos',vegetarian:'Vegetarianos',minor:'Menores',missing:'Sin DNI',noseat:'Sin ubicación',civil:'Civil'}).map(([k,l])=>`<label><input type="checkbox" name="metric_${k}" ${guestPrefs.metrics.includes(k)?'checked':''}>${l}</label>`).join('')}</div><h3>Datos visibles en tarjetas y tabla</h3><div class="guest-check-grid">${Object.entries(guestColumns).map(([k,l])=>`<label><input type="checkbox" name="col_${k}" ${guestPrefs.columns.includes(k)?'checked':''}>${l}</label>`).join('')}</div>${guestPrefs.saved.length?'<label><input type="checkbox" name="clear_saved"> Borrar mis vistas guardadas</label>':''}<p>Esta configuración queda guardada en este navegador.</p></div>`,async d=>{guestPrefs.metrics=Object.keys(d).filter(k=>k.startsWith('metric_')).map(k=>k.slice(7));guestPrefs.columns=Object.keys(d).filter(k=>k.startsWith('col_')).map(k=>k.slice(4));if(d.clear_saved)guestPrefs.saved=[];persistGuestPrefs();$('#modal').close();render()})}
function guestBulkEdit(){const ids=new Set(guestSelectedRows().map(g=>g.id));modal(`Editar ${ids.size} personas`,`<p class="full">Se aplicará a las ${ids.size} personas seleccionadas de la vista actual.</p><label>Confirmación<select name="status">${guestOptions(['Confirmado','Pendiente','No viene'].map(v=>[v,v]),'','Sin cambiar')}</select></label><label>Grupo<input name="group" placeholder="Dejar vacío para conservar"></label><label>Menú<select name="menu">${guestOptions(['Ninguna','Celíaco','Vegetariano','Vegano'].map(v=>[v,v]),'','Sin cambiar')}</select></label><label>Civil<select name="civil"><option value="">Sin cambiar</option><option value="yes">Invitar al civil</option><option value="no">Quitar de la lista del civil</option></select></label><p class="full">Marcar “No viene” también libera su lugar en el plano.</p>`,async d=>{const next=structuredClone(db);for(const g of next.guests.filter(g=>ids.has(g.id))){if(d.status)g.status=d.status;if(d.group.trim())g.group=d.group.trim();if(d.menu)g.menu=d.menu;if(d.civil)g.civil=d.civil==='yes'}if(await save(next)){guestSelection.clear();$('#modal').close();render()}})}
function bindGuestMobile(){
 document.querySelectorAll('[data-gview]').forEach(b=>b.onclick=()=>guestReset(b.dataset.gview));
 document.querySelectorAll('[data-gfilter]').forEach(s=>s.onchange=()=>{guestFilters[s.dataset.gfilter]=s.value;guestSelection.clear();render()});
 $('#guest-search').oninput=e=>{const pos=e.target.selectionStart;search=e.target.value;guestSelection.clear();render();$('#guest-search').focus();$('#guest-search').setSelectionRange(pos,pos)};
 $('#guest-sort').onchange=e=>{guestSort=e.target.value;render()};
 $('#guest-clear').onclick=()=>guestReset(guestView);$('#guest-empty-reset')?.addEventListener('click',()=>guestReset());
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{guestPrefs.mode=b.dataset.mode;persistGuestPrefs();render()});
 document.querySelectorAll('[data-metric]').forEach(b=>b.onclick=()=>{const k=b.dataset.metric;guestReset(k==='pending'?'pending':k==='civil'?'civil':'confirmed');if(k==='celiac'||k==='vegetarian')guestFilters.diet=k;if(k==='minor')guestFilters.age='Menor';if(k==='missing')guestFilters.dni='missing';if(k==='noseat')guestFilters.seat='missing';render()});
 document.querySelectorAll('[data-menu-pick]').forEach(b=>b.onclick=()=>{guestFilters.diet=guestFilters.diet===b.dataset.menuPick?'':b.dataset.menuPick;render()});
 document.querySelectorAll('[data-guest-check]').forEach(c=>c.onchange=()=>{c.checked?guestSelection.add(c.dataset.guestCheck):guestSelection.delete(c.dataset.guestCheck);render()});
 $('#guest-select-all').onchange=e=>{guestSelection=e.target.checked?new Set(guestFilteredRows().map(g=>g.id)):new Set();render()};
 $('#guest-selection-clear')?.addEventListener('click',()=>{guestSelection.clear();render()});$('#guest-bulk')?.addEventListener('click',guestBulkEdit);
 $('#guest-customize').onclick=guestCustomize;$('#guest-export').onclick=guestExport;$('#country-export')?.addEventListener('click',()=>guestCountryExport(guestSelectedRows()));
 document.querySelectorAll('[data-dni]').forEach(b=>b.onclick=()=>guestEditDni(b.dataset.dni));
 document.querySelectorAll('[data-link-response]').forEach(b=>b.onclick=()=>linkResponse(b.dataset.linkResponse));
 document.querySelectorAll('[data-accept-response]').forEach(b=>b.onclick=()=>{const g=db.guests.find(g=>g.id===b.dataset.acceptResponse);modal('Agregar respuesta a la lista',`<p class="full">¿Agregar a <b>${esc(g.name)}</b> como una persona nueva? Hacelo solo si no figura con otro nombre en la lista base.</p>`,async()=>{const next=structuredClone(db),row=next.guests.find(x=>x.id===g.id);row.baseIncluded=true;row.matchMethod='Persona nueva revisada';if(await save(next))$('#modal').close()})});
 $('#guest-save-view').onclick=()=>modal('Guardar esta vista',field('name','Nombre de la vista','','text',true),async d=>{if(!d.name.trim())return;const view={name:d.name.trim().slice(0,60),view:guestView,filters:{...guestFilters},search,sort:guestSort,mode:guestPrefs.mode,columns:[...guestPrefs.columns]};guestPrefs.saved=guestPrefs.saved.filter(v=>v.name!==view.name);guestPrefs.saved.push(view);guestPrefs.saved=guestPrefs.saved.slice(-12);persistGuestPrefs();$('#modal').close();render()});
 document.querySelectorAll('[data-saved-view]').forEach(b=>b.onclick=()=>{const v=guestPrefs.saved[+b.dataset.savedView];guestView=v.view;guestFilters={...v.filters};search=v.search;guestSort=v.sort;guestPrefs.mode=v.mode;guestPrefs.columns=[...v.columns];guestSelection.clear();render()});
}
function linkResponse(id){const response=db.guests.find(g=>g.id===id);const options=db.guests.filter(g=>g.baseIncluded&&!g.respondedAt).sort((a,b)=>a.name.localeCompare(b.name,'es'));modal('Vincular respuesta',`<p class="full">Respuesta de <b>${esc(response.name)}</b>. Elegí su nombre en la lista base. Se conservarán menú, mensaje y ubicación.</p><label class="full">Persona en la lista base<select name="target" required><option value="">Elegir persona…</option>${options.map(g=>`<option value="${esc(g.id)}" ${(response.crossCandidates||[]).length===1&&response.crossCandidates[0]===g.id?'selected':''}>${esc(g.name)}${(response.crossCandidates||[]).includes(g.id)?' · posible coincidencia':''}</option>`).join('')}</select></label>`,async d=>{const next=structuredClone(db),r=next.guests.find(g=>g.id===id),b=next.guests.find(g=>g.id===d.target);if(!b||b.respondedAt)return toast('Elegí una persona sin respuesta vinculada.');if(guestDni(r)&&guestDni(b)&&guestDni(r)!==guestDni(b))return toast('Los DNI son diferentes. Revisá los documentos antes de vincular.');Object.assign(r,{baseIncluded:true,baseName:b.baseName||b.name,group:b.group,suggestedTable:b.suggestedTable,matchMethod:'Vinculación manual',table:r.table||b.table,dni:r.dni||b.dni||'',civil:Boolean(r.civil||b.civil)});r.notes=[r.notes,b.notes].filter(Boolean).join(' | ');delete r.crossCandidates;for(const t of next.layout?.items||[])t.guests=[...new Set(t.guests.map(g=>g===b.id?r.id:g))];next.guests=next.guests.filter(g=>g.id!==b.id);if(await save(next))$('#modal').close()})}
