import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import {validate} from '../lib/validate.js';
const base=()=>({providers:[],guests:[{id:'g',name:'Ana',status:'Confirmado',ageGroup:'Adulto'}],funds:{ARS:0,USD:0},layout:{room:{width:20,depth:15},items:[]}});
test('zones accept dimensions but cannot seat guests',()=>{const d=base();d.layout.items=[{id:'bar',name:'Barra',type:'bar',capacity:0,guests:[],x:0,y:0,width:4,depth:1.5}];assert.equal(validate(d),d);d.layout.items[0].guests=['g'];assert.throws(()=>validate(d))});
test('couple table can seat guests; physical bounds and small rooms rejected',()=>{const d=base();d.layout.items=[{id:'head',name:'Novios',type:'headtable',capacity:2,guests:['g'],x:10,y:10,width:3,depth:1.5}];assert.equal(validate(d),d);d.layout.items[0].x=99;assert.throws(()=>validate(d));d.layout.items[0].x=0;d.layout.room.width=2;assert.throws(()=>validate(d))});
test('resizing room preserves physical dimensions and contains furniture',()=>{const c=vm.createContext({db:{}});vm.runInContext(fs.readFileSync(new URL('../planner.js',import.meta.url),'utf8'),c);c.layout={room:{width:20,depth:15},items:[{id:'a',type:'table',width:3,depth:3,x:75,y:70}]};const result=vm.runInContext('planReframe(layout,10,8)',c);assert.equal(result.items[0].width,3);assert.equal(result.items[0].depth,3);assert.equal(result.items[0].x,70);assert.equal(result.items[0].y,62.5);assert.throws(()=>vm.runInContext('planReframe(layout,2,8)',c))});

test('L rooms keep furniture out of each of the four cutouts',()=>{const c=vm.createContext({db:{}});vm.runInContext(fs.readFileSync(new URL('../planner.js',import.meta.url),'utf8'),c);for(const corner of ['nw','ne','sw','se']){const d=base();d.layout.room={width:20,depth:15,shape:'l',cutCorner:corner,cutWidth:10,cutDepth:8};d.layout.items=[{id:'bar',name:'Barra',type:'bar',capacity:0,guests:[],width:3,depth:2,x:corner.includes('w')?0:70,y:corner.includes('n')?0:70}];assert.throws(()=>validate(d),/recorte/);c.layout=d.layout;d.layout=vm.runInContext('planReframe(layout,20,15)',c);assert.equal(validate(d),d);assert.equal(d.layout.items[0].width,3);d.layout.room.cutWidth=20;assert.throws(()=>validate(d),/Recorte/)}});
test('L rejects furniture that cannot fit either arm',()=>{const c=vm.createContext({db:{}});vm.runInContext(fs.readFileSync(new URL('../planner.js',import.meta.url),'utf8'),c);c.layout={room:{width:10,depth:10,shape:'l',cutCorner:'se',cutWidth:8,cutDepth:8},items:[{type:'table',width:3,depth:3,x:0,y:0}]};assert.throws(()=>vm.runInContext('planReframe(layout,10,10)',c),/no entra/)});
test('named tables can be created, assigned, moved, renamed and removed from floor',async()=>{const d=base();d.guests.push({id:'g2',name:'Augusto',status:'Confirmado',ageGroup:'Adulto'});let callback,chosen=[],toastMessage='';const control={setAttribute(){},addEventListener(){},close(){},value:'',textContent:''};const c=vm.createContext({db:d,busy:false,structuredClone,crypto:{randomUUID:()=>String(Math.random())},esc:String,field:()=>'',guestUnlinked:()=>false,guestNormalize:x=>x.toLowerCase(),$:()=>control,modal:(title,fields,submit)=>{callback=submit},toast:m=>{toastMessage=m},document:{querySelectorAll:s=>s==='[data-seat-choice]:checked'?chosen.map(id=>({dataset:{seatChoice:id}})):[]},save:async next=>{validate(next);c.db=next;return true}});vm.runInContext(fs.readFileSync(new URL('../planner.js',import.meta.url),'utf8'),c);
vm.runInContext('editNamedTable()',c);await callback({name:'Titulares',capacity:'1'});const first=c.db.layout.items[0];assert.equal(first.placed,false);assert.equal(first.name,'Titulares');c.id=first.id;
vm.runInContext('chooseTableGuests(id)',c);chosen=['g','g2'];await callback();assert.match(toastMessage,/seleccionaste 2/);assert.equal(c.db.layout.items[0].guests.length,0);chosen=['g'];await callback();assert.equal(c.db.guests[0].table,'Titulares');
vm.runInContext('editNamedTable()',c);await callback({name:'Ana, Augusto y tíos borrachos',capacity:'10'});c.id2=c.db.layout.items[1].id;vm.runInContext('chooseTableGuests(id2)',c);chosen=['g'];await callback();assert.equal(c.db.layout.items[0].guests.length,0);assert.equal(c.db.layout.items[1].guests[0],'g');
vm.runInContext('editNamedTable(id2)',c);await callback({name:'Amicus Curiae',capacity:'10'});assert.equal(c.db.guests[0].table,'Amicus Curiae');await vm.runInContext('placeNamedTable(id2,true)',c);assert.equal(c.db.layout.items[1].placed,true);await vm.runInContext('placeNamedTable(id2,false)',c);assert.equal(c.db.layout.items[1].placed,false);assert.equal(c.db.layout.items[1].guests[0],'g');c.db.layout.room={width:3,depth:3,shape:'l',cutCorner:'se',cutWidth:2,cutDepth:2};assert.equal(validate(c.db),c.db);const r=vm.runInContext('planReframe(db.layout,3,3)',c);assert.equal(r.items[1].guests[0],'g');assert.match(vm.runInContext('tablesView()',c),/Amicus Curiae/);c.db.layout.items[1].placed=true;assert.throws(()=>validate(c.db));});
test('blank capacity permits free grouping and later optional limits',async()=>{let submit,chosen=[],message='';const d=base();d.guests.push({id:'g2',name:'Augusto',status:'Pendiente',ageGroup:'Adulto'});const el={setAttribute(){},addEventListener(){},close(){}};const c=vm.createContext({db:d,busy:false,structuredClone,crypto:{randomUUID:()=> 'new'},esc:String,field:()=>'',guestUnlinked:()=>false,guestNormalize:x=>x.toLowerCase(),$:()=>el,modal:(title,fields,fn)=>{submit=fn},toast:m=>message=m,document:{querySelectorAll:s=>s==='[data-seat-choice]:checked'?chosen.map(id=>({dataset:{seatChoice:id}})):[]},save:async next=>{validate(next);c.db=next;return true}});vm.runInContext(fs.readFileSync(new URL('../planner.js',import.meta.url),'utf8'),c);vm.runInContext('editNamedTable()',c);await submit({name:'Los del cole',capacity:''});assert.equal(c.db.layout.items[0].capacity,null);vm.runInContext('chooseTableGuests("new")',c);chosen=['g','g2'];await submit();assert.equal(c.db.layout.items[0].guests.length,2);assert.match(vm.runInContext('tablesView()',c),/2 personas/);vm.runInContext('editNamedTable("new")',c);await submit({name:'Los del cole',capacity:'1'});assert.equal(c.db.layout.items[0].capacity,null);assert.match(message,/invitados actuales/);await submit({name:'Los del cole',capacity:'3'});assert.equal(c.db.layout.items[0].capacity,3);vm.runInContext('editNamedTable("new")',c);await submit({name:'Los del cole',capacity:''});await vm.runInContext('assignGuest("g")',c);await vm.runInContext('assignGuest("g","new")',c);assert.equal(c.db.layout.items[0].guests.length,2);assert.equal(c.db.layout.items[0].capacity,null)});
