export function validate(d){if(!d||!Array.isArray(d.providers)||!Array.isArray(d.guests)||d.providers.length>1000||d.guests.length>3000)throw Error('Datos inválidos');for(const p of d.providers){if(typeof p.id!=='string'||typeof p.name!=='string'||!p.name.trim()||p.name.length>200||!['ARS','USD'].includes(p.currency)||!['confirmed','estimate','unknown','gift','external'].includes(p.kind))throw Error('Proveedor inválido');for(const k of ['cost','paid'])if(p[k]!==null&&(!Number.isFinite(p[k])||p[k]<0))throw Error('Importe inválido');if(p.cost!==null&&p.paid!==null&&p.paid>p.cost)throw Error('El pago supera el importe')}for(const g of d.guests)if(typeof g.id!=='string'||typeof g.name!=='string'||!g.name.trim()||!['Pendiente','Confirmado','No viene'].includes(g.status)||!['Adulto','Menor','Sin informar'].includes(g.ageGroup))throw Error('Invitado inválido');for(const g of d.guests){if(g.dni!==undefined&&(typeof g.dni!=='string'||g.dni!==''&&!/^\d{7,8}$/.test(g.dni)))throw Error('DNI inválido');if(g.civil!==undefined&&typeof g.civil!=='boolean')throw Error('Civil inválido')}for(const c of ['ARS','USD'])if(!Number.isFinite(d.funds?.[c])||d.funds[c]<0)throw Error('Fondo inválido');if(d.layout){
const defaults={table:[3,3],living:[3,2],headtable:[3,1.5],bar:[4,1.5],dj:[3,2],photo:[3,2],dance:[5,5],entrance:[2,1],custom:[3,2]};
if(!Array.isArray(d.layout.items)||d.layout.items.length>100)throw Error('Plano inválido');
const room=d.layout.room;
if(room&&(!Number.isFinite(room.width)||!Number.isFinite(room.depth)||room.width<3||room.depth<3||room.width>80||room.depth>80))throw Error('Medidas del salón inválidas');
if(room?.shape!==undefined&&!['rectangle','l'].includes(room.shape))throw Error('Forma del salón inválida');
if(room?.shape==='l'&&(!['nw','ne','sw','se'].includes(room.cutCorner)||!Number.isFinite(room.cutWidth)||!Number.isFinite(room.cutDepth)||room.cutWidth<.5||room.cutDepth<.5||room.cutWidth>room.width-.5||room.cutDepth>room.depth-.5))throw Error('Recorte del salón inválido');
const seated=new Set(),spaces=new Set();for(const t of d.layout.items){
const seatable=['table','living','headtable'].includes(t.type);
if(typeof t.id!=='string'||spaces.has(t.id)||typeof t.name!=='string'||!t.name.trim()||t.name.length>200||!Object.hasOwn(defaults,t.type)||(seatable?!(t.capacity===null||(Number.isInteger(t.capacity)&&t.capacity>=1&&t.capacity<=100)):t.capacity!==0)||!Number.isFinite(t.x)||!Number.isFinite(t.y)||t.x<0||t.x>100||t.y<0||t.y>100||!Array.isArray(t.guests)||(t.capacity!==null&&t.guests.length>t.capacity))throw Error('Espacio inválido');
for(const k of ['width','depth'])if(t[k]!==undefined&&(!Number.isFinite(t[k])||t[k]<.5||t[k]>80))throw Error('Medidas del espacio inválidas');
if(t.placed!==undefined&&typeof t.placed!=='boolean')throw Error('Ubicación inválida');if(t.placed===false&&!seatable)throw Error('Solo mesas y livings pueden quedar sin ubicar');if(room&&t.placed!==false){const width=t.width??defaults[t.type][0],depth=t.depth??defaults[t.type][1];if(t.x/100*room.width+width>room.width+.011||t.y/100*room.depth+depth>room.depth+.011)throw Error('El espacio queda fuera del salón');if(room.shape==='l'){const cx=room.cutCorner.includes('w')?0:room.width-room.cutWidth,cy=room.cutCorner.includes('n')?0:room.depth-room.cutDepth,x=t.x/100*room.width,y=t.y/100*room.depth;if(x<cx+room.cutWidth-.001&&x+width>cx+.001&&y<cy+room.cutDepth-.001&&y+depth>cy+.001)throw Error('El espacio queda dentro del recorte de la L')}}
spaces.add(t.id);for(const id of t.guests){if(seated.has(id)||!d.guests.some(g=>g.id===id&&g.status!=='No viene'))throw Error('Ubicación de invitado inválida');seated.add(id)}}}return d}
